"use client";

import { ImageGuidePage, type ImageGuideTab } from "@/components/tools/image-guide-page";

const TABS: readonly ImageGuideTab[] = [
  {
    id: "chu-hoa",
    label: "Chữ hoa",
    basePath: "/download/huong-dan-chu-hoa",
    files: [
      "A.jpg",
      "Ă.jpg",
      "Ă 2.jpg",
      "Â.jpg",
      "B.jpg",
      "C.jpg",
      "D.jpg",
      "Đ.jpg",
      "E.jpg",
      "E 2.jpg",
      "G.jpg",
      "H.jpg",
      "J.jpg",
      "K.jpg",
      "L.jpg",
      "M.jpg",
      "M kiểu 2.jpg",
      "N.jpg",
      "N 2.jpg",
      "O.jpg",
      "Ô.jpg",
      "Ơ.jpg",
      "P.jpg",
      "Q.jpg",
      "Q Kiểu 2.jpg",
      "R.jpg",
      "S.jpg",
      "T.jpg",
      "U.jpg",
      "Ư.jpg",
      "V.jpg",
      "V 2.jpg",
      "X.jpg",
      "Y.jpg",
    ],
  },
  {
    id: "chu-thuong",
    label: "Chữ thường",
    basePath: "/download/huong-dan-chu-thuong",
    files: [
      "a.jpg",
      "ă.jpg",
      "â.jpg",
      "b.jpg",
      "c.jpg",
      "d.jpg",
      "đ.jpg",
      "e.jpg",
      "ê.jpg",
      "g.jpg",
      "h.jpg",
      "i.jpg",
      "k.jpg",
      "l.jpg",
      "m.jpg",
      "n.jpg",
      "o.jpg",
      "ô.jpg",
      "ơ.jpg",
      "p.jpg",
      "q.jpg",
      "r.jpg",
      "s.jpg",
      "t.jpg",
      "u.jpg",
      "ư.jpg",
      "v.jpg",
      "x.jpg",
      "y.jpg",
    ],
  },
  {
    id: "chu-so",
    label: "Chữ số",
    basePath: "/download/huong-dan-chu-so",
    files: ["0.jpg", "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg"],
  },
  {
    id: "viet-net",
    label: "Viết nét",
    basePath: "/download/huong-dan-viet-net",
    files: [
      "a.jpg",
      "b.jpg",
      "c.jpg",
      "d.jpg",
      "đ.jpg",
      "e.jpg",
      "g.jpg",
      "h.jpg",
      "i.jpg",
      "k.jpg",
      "l.jpg",
      "m.jpg",
      "n.jpg",
      "o.jpg",
      "p.jpg",
      "q.jpg",
      "r.jpg",
      "s.jpg",
      "t.jpg",
      "u.jpg",
      "v.jpg",
      "x.jpg",
      "y.jpg",
    ],
  },
] as const;

export default function HuongDanVietPage() {
  return (
    <ImageGuidePage
      title="Hướng dẫn viết chữ tiểu học"
      intro="Chọn từng tab để xem trước hình ảnh hướng dẫn. Bạn có thể phóng to, thu nhỏ, tải từng hình hoặc tải toàn bộ tài liệu ở góc trên bên phải."
      fullZipHref="/download/huong-dan.zip"
      tabs={TABS}
    />
  );
}

